---
- name: This is the cleanup script for Lesson 2 Topic C lab
  hosts: localhost
  become: true
  gather_facts: false
  vars:
    users:
      - "Tony"
      - "Tim"
      - "Manu"
      - "Gregg"
    mygroup: Spurs
    
  tasks:
    - name: Removes the group for lab
      group:
        name: "{{ mygroup }}"
        state: absent
        
    - name: Remove the users for lab
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      loop: "{{ users }}"

    - name: Copy a new "sudoers" file into place, after passing validation with visudo
      ansible.builtin.copy:
        src: /root/.sudoerscopy
        dest: /etc/sudoers
        remote_src: yes
        validate: /usr/sbin/visudo -csf %s

    - name: Remove copied file
      file:
        path: /root/.sudoerscopy
        state: absent

    - name: Remove any files created in /etc/sudoers.d
      shell: rm -rf /etc/sudoers.d/*
      args:
        executable: /bin/bash
