---
- name: This sets up Lesson 6 Topic B Lab
  hosts: localhost
  become: true
  tasks:

    - name: copy journal config file
      copy:
        src: /etc/systemd/journald.conf
        dest: /root/.journal
        remote_src: yes

    - name: Turn off persistent journaling
      lineinfile:
        path: /etc/systemd/journald.conf
        regexp: '^Storage='
        line: '#Storage=auto'
