---
- name: This sets up Lesson 6 Lab
  hosts: localhost
  become: true
  tasks:
    - name: copy rsyslog.d
      copy:
        src: /etc/rsyslog.d
        dest: /root/.rsyslog
        remote_src: yes
