---
- name: This sets up Lesson 4 lab 
  hosts: localhost
  become: true
  tasks:
    - name: Enable and start cups service
      service:
        name: cups
        enabled: yes
        state: started

    - name: Disable and stop chronyd
      service: 
        name: chronyd
        enabled: no
        state: stopped

   #- name: make a copy of fstab file
   #   copy:
   #     src: /etc/fstab
   #     dest: /root/.fstabcopy
   #     remote_src: yes
