---
- name: This cleans up Lesson 4 lab
  hosts: localhost
  become: true
  ignore_errors: yes
  tasks:
    - name: unmount VG
      mount:
        path: /BestTeam
        state: absent

    - name: unmount /BestTeam
      shell: umount /BestTeam

    - name: Remove the logical volume OozmaKappa
      lvol:
        vg: MU
        lv: OozmaKappa
        state: absent
        force: yes

    - name: Remove a volume group with name MU
      lvg:
        vg: MU
        state: absent
        force: yes

    - name: Remove /BestTeam directory
      shell: rm -rf /BestTeam

    - name: unmount partition 2
      mount:
        path: /Scaring101
        state: absent
        
    - name: unmount partition 2 again
      shell: umount /Scaring101

    - name: Remove /Scaring101 directory
      shell: rm -rf /Scaring101

    - name: unmount partition 3
      mount:
        path: /ScreamEnergy
        state: absent

    - name: unmount VG RoarOmega
      mount:
        path: /ScareGames
        state: absent

    - name: Remove the logical volume Randall
      lvol:
        vg: RoarOmega
        lv: Randall
        state: absent
        force: yes

    - name: Remove a volume group with name RoarOmega
      lvg:
        vg: RoarOmega
        state: absent

    - name: Remove /ScreamEnergy directory
      shell: rm -rf /ScreamEnergy

    - name: Remove /ScareGames directory
      shell: rm -rf /ScareGames

    - name: Remove signature from sdd1
      shell: 
        cmd: wipefs -a /dev/sdd1

    - name: Remove signature from sdd2
      shell: 
        cmd: wipefs -a /dev/sdd2

    - name: Remove signature from sdd3
      shell: 
        cmd: wipefs -a /dev/sdd3

    - name: Remove signature from sdd4
      shell: 
        cmd: wipefs -a /dev/sdd4

    - name: Remove signature from sdd5
      shell: 
        cmd: wipefs -a /dev/sdd5

    - name: read sdd info
      parted: device=/dev/sdd unit=MiB
      register: sdd_info

    - name: This deletes all partitions on sdd
      parted:
        device: /dev/sdd
        number: "{{ item.num }}"
        state: absent
      with_items:
       - "{{ sdd_info.partitions }}"

    - name: Copy a new fstab file into place
      copy:
        src: /root/.fstabcopy
        dest: /etc/fstab
        remote_src: yes

    - name: Remove copied file
      file:
        path: /root/.fstabcopy
        state: absent
