---
- name: Configure fedora workstation
  hosts: localhost
  become: yes

  tasks:
    - name: Create user for lab activity
      user:
        name: student
        state: present
        password: "{{ 'Pa22w0rd' | password_hash('sha512') }}"
        groups: wheel


    - name: Install needed tools
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - yum-utils
        - sysstat
        - ioping
        - emacs
        - vim-X11
