---
- name: This is the setup script for Lesson 2 Topic C lab
  hosts: localhost
  become: true
  gather_facts: false
  vars:
    users:
      - "Tim"
      - "Tony"
      - "Manu"
  
  tasks:
    - name: Create the users for lab
      user:
        name: "{{ item }}"
      loop: "{{ users }}"
