---
- name: This cleans up Lesson 4 Topic A lab
  hosts: localhost
  become: true
  ignore_errors: yes
  tasks:
    - name: unmount partitions
      mount:
        path: /Flask
        state: unmounted

    - name: unmount partitions
      mount:
        path: /Beaker
        state: unmounted

    - name: Remove mount point
      file:
        path: /Flask
        state: absent

    - name: Remove mount point
      file:
        path: /Beaker
        state: absent

    - name: Remove signature from sdd3
      shell: 
        cmd: wipefs -a /dev/sdd3

    - name: Remove signature from sdd4
      shell: 
        cmd: wipefs -a /dev/sdd4

    - name: Remove signature from sdd5
      shell: 
        cmd: wipefs -a /dev/sdd5

    - name: read sdd info
      parted: device=/dev/sdd unit=MiB
      register: sdd_info

    - name: This deletes all partitions on sdd
      parted:
        device: /dev/sdd
        number: "{{ item.num }}"
        state: absent
      with_items:
       - "{{ sdd_info.partitions }}"

    - name: Copy a new fstab file into place
      copy:
        src: /root/.fstabcopy
        dest: /etc/fstab
        remote_src: yes

    - name: Remove copied file
      file:
        path: /root/.fstabcopy
        state: absent
