---
- name: This sets up Lesson 4 Topic A lab
  hosts: localhost
  become: true
  tasks:
    - name: This creates partitions needed for lab
      parted:
        device: /dev/sdd
        number: 1
        state: present
        part_end: 101MiB
        part_type: primary

    - name: This creates partitions needed for lab
      parted:
        device: /dev/sdd
        number: 2
        state: present
        part_start: 101MiB
        part_end: 221MiB
        part_type: primary

    - name: make a copy of fstab file
      copy: 
        src: /etc/fstab
        dest: /root/.fstabcopy
        remote_src: yes
