---
- name: This sets up Lesson 7 lab
  hosts: localhost
  become: true
  tasks:
    - name: make a copy of 40_custom file
      copy: 
        src: /etc/grub.d/40_custom
        dest: /root/.40custom
        remote_src: yes

