---
- name: This sets up Lesson 4 Topic B lab
  hosts: localhost
  become: true
  tasks:
    - name: make a copy of fstab file
      copy: 
        src: /etc/fstab
        dest: /root/.fstabcopy
        remote_src: yes

