---
- name: This cleans up Lesson 8 lab 
  hosts: localhost
  become: true
  tasks:
    - name: Enable and start chronyd service
      service:
        name: chronyd
        enabled: yes
        state: started
   
    - name: Unmask cups
      shell: systemctl unmask cups

    - name: Disable and stop cups
      service:
        name: cups
        enabled: no
        state: stopped

    - name: Turn swap off on /dev/sdd1
      shell: swapoff /dev/sdd1

    - name: Remove signature from sdd1
      shell:
        cmd: wipefs -a /dev/sdd1

    - name: read sdd info
      parted: device=/dev/sdd unit=MiB
      register: sdd_info

    - name: This deletes all partitions on sdd
      parted:
        device: /dev/sdd
        number: "{{ item.num }}"
        state: absent
      with_items:
       - "{{ sdd_info.partitions }}"

    - name: Copy a new fstab file into place
      copy:
        src: /root/.fstabcopy
        dest: /etc/fstab
        remote_src: yes

    - name: Remove copied file
      file:
        path: /root/.fstabcopy
        state: absent
                                 

