---
- name: This sets up the Lesson 2 Knowledge check lab
  hosts: localhost
  become: true
  tasks:
    - name: This creates a copy of the sudoers file
      ansible.builtin.copy:
        src: /etc/sudoers
        dest: /root/.sudoerscopy
        remote_src: yes
        validate: /usr/sbin/visudo -csf %s

    - name: This creates a copy of the login.defs file
      ansible.builtin.copy:
        src: /etc/login.defs
        dest: /root/.logincopy
        remote_src: yes
