---
- name: This cleans up Lab 12
  hosts: localhost
  become: true
  tasks:
    - name: Remove all files in rsyslog directory
      shell: rm -rf /etc/rsyslog.d/*

    - name: copy rsyslog.d back into place
      copy:
        src: /root/.rsyslog/rsyslog.d
        dest: /etc
        remote_src: yes

    - name: Remove copied file
      file:
        path: /root/.rsyslog
        state: absent

    - name: copy journal config file
      copy:
        src: /etc/systemd/journald.conf
        dest: /etc/systemd/journald.conf
        remote_src: yes

    - name: Remove copied file
      file:
        path: /root/.journal
        state: absent

    - name: Remove messages-debug file
      file:
        path: /var/log/messages-debug
        state: absent

    - name: Remove recentlogs file
      file:
        path: /root/recentlogs.txt
        state: absent

    - name: Remove httpd package
      yum:
        name: httpd
        state: absent

    - firewalld:
        service: https
        permanent: yes
        state: disabled

    - firewalld:
        port: 443/tcp
        permanent: yes
        state: disabled

    - firewalld:
        service: http
        permanent: yes
        state: disabled

    - firewalld:
        port: 80/tcp
        permanent: yes
        state: disabled

    - firewalld:
        service: https
        permanent: no
        state: disabled

    - firewalld:
        port: 443/tcp
        permanent: no
        state: disabled

    - firewalld:
        service: http
        permanent: no
        state: disabled

    - firewalld:
        port: 80/tcp
        permanent: no
        state: disabled

    - name: Remove www directory
      shell: rm -rf /var/www
