---
- name: This sets up Lab 12
  hosts: localhost
  become: true
  tasks:
    - name: copy rsyslog.d
      copy:
        src: /etc/rsyslog.d
        dest: /root/.rsyslog
        remote_src: yes

    - name: copy journal config file
      copy:
        src: /etc/systemd/journald.conf
        dest: /root/.journal
        remote_src: yes

    - name: Turn off persistent journaling
      lineinfile:
        path: /etc/systemd/journald.conf
        regexp: '^Storage='
        line: '#Storage=auto'

    - name: Remove httpd package
      yum:
        name: httpd
        state: absent

    - firewalld:
        service: https
        permanent: yes
        state: disabled

    - firewalld:
        port: 443/tcp
        permanent: yes
        state: disabled

    - firewalld:
        service: http
        permanent: yes
        state: disabled

    - firewalld:
        port: 80/tcp
        permanent: yes
        state: disabled

    - firewalld:
        service: https
        permanent: no
        state: disabled

    - firewalld:
        port: 443/tcp
        permanent: no
        state: disabled

    - firewalld:
        service: http
        permanent: no
        state: disabled

    - firewalld:
        port: 80/tcp
        permanent: no
        state: disabled

    - name: create web directory
      shell: mkdir -p /var/www/html

    - name: create index file
      shell: echo "You did it!!" > /var/www/html/index.html
