---
- name: Configure centos server
  hosts: localhost
  become: yes

  tasks:
    - name: Create group admin for lab activity
      group:
        name: admin
        state: present

    - name: Create user student for lab activity
      user:
        name: student
        state: present
        password: "{{ 'Pa22w0rd' | password_hash('sha512') }}"
        groups: admin


    - name: Install needed tools
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - bash-completion
